export const POMELO_CONNECT_TOKEN_NONCE_BYTES = 24;
export const POMELO_KEY_BYTES = 32;
export const POMELO_ENCRYPTED_PRIVATE_CONNECT_TOKEN_BYTES = 1024;
export const POMELO_CONNECT_TOKEN_BYTES = 2048;
export const POMELO_ADDRESS_IPV4 = 1;
export const POMELO_ADDRESS_IPV6 = 2;
export const POMELO_MESSAGE_CAPACITY = 16 * 1024; // 16KiB
